# Site settings
baseurl = "/"
languageCode = "en"
title = "Program Obscura"
theme = "obscura"

[params]
	author = "Bienvenido Rodriguez"
	description = "My (mis) adventures through technology"
	bio = "Scratching, scribbling and smearing at the cross section of technology, philosophy and investing while staying ahead of a creeping self identity crisis."

	twitter = "b17z_"

	enableRSS = true
	enableToc = true

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true

	enableTwitterCard = true

	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "Home"
	about = "About Me"
	archive = "Archives"
	subscribe = "Subscribe"

	olderPosts = "Older"
	newerPosts = "Newer"
	copyright = "Copyright B17Z 2018"

	# show latest posts in single page
	showLatestPosts = true
	readMore = "Read More"

	# Share
	enableShare = true
	tweet = "Tweet"
	share = "Share"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"


# Add additional social link entries underneath
[social]
	twitter-square = "https://www.twitter.com/b17z_"
    github-square = "https://www.github.com/b17z"
